### ISSUE TITLE
How I get  CONVERGENCE_URL

### ISSUE THREAD

**Issue by omrsfylmz** [convergencelabs/mxgraph-demo#13]
I looked your website and some extra resources but I didn't find where I get Convergence url can you explain where I get this.

**Comment by mmacfadden** [comment]
Hello!  The CONVERGENCE_URL would need to point to a locally running instance of convergence. The easiest way would be to run with docker.

```
docker run -p "8000:80" convergencelabs/convergence-omnibus
```

See here for more info:

https://hub.docker.com/r/convergencelabs/convergence-omnibus

**Comment by omrsfylmz** [comment]
Thanks
